/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Persistencia.SesionData;
import Persistencia.miConexion;
import entidades.Sesion;
import entidades.Instalacion;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 * @author Grupo10
 *
 * Altamirano Karina Gianfranco Antonacci Matías Bequis Marcos Ezequiel Dave
 * Natalia
 */
public class vistaHistorialSesiones extends javax.swing.JInternalFrame {

    private miConexion connection;
    private SesionData sesionData;
    private DateTimeFormatter formatoFecha;
    private DateTimeFormatter formatoHora;
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    /**
     * Creates new form vistaHistorialSesiones
     */
    public vistaHistorialSesiones() {
        initComponents();
        this.getContentPane().setBackground(new Color(155, 216, 185));
        try {
            connection = new miConexion("jdbc:mariadb://localhost:3306/gp10_entre_dedos", "root", "");
            sesionData = new SesionData(connection);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage());
        }
        
        formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        formatoHora = DateTimeFormatter.ofPattern("HH:mm");
        
        armarCabecera();
        cargarSesiones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtSesiones = new javax.swing.JTable();
        jbActualizar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Historial de Sesiones");

        jtSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jtSesiones);

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbActualizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        cargarSesiones();
    }//GEN-LAST:event_jbActualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JTable jtSesiones;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.setRowCount(0);
        modelo.setColumnCount(0);
        
        modelo.addColumn("Fecha");
        modelo.addColumn("Horario");
        modelo.addColumn("Cliente");
        modelo.addColumn("Tratamiento");
        modelo.addColumn("Masajista");
        modelo.addColumn("Consultorio");
        modelo.addColumn("Instalaciones");
        modelo.addColumn("Estado");
        
        jtSesiones.setModel(modelo);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        jtSesiones.getTableHeader().setDefaultRenderer(centerRenderer);

        DefaultTableCellRenderer centrarCeldas = new DefaultTableCellRenderer();
        centrarCeldas.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < jtSesiones.getColumnCount(); i++) {
            jtSesiones.getColumnModel().getColumn(i).setCellRenderer(centrarCeldas);
        }
        
        jtSesiones.getColumnModel().getColumn(0).setPreferredWidth(100);
        jtSesiones.getColumnModel().getColumn(1).setPreferredWidth(80);
        jtSesiones.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtSesiones.getColumnModel().getColumn(3).setPreferredWidth(150);
        jtSesiones.getColumnModel().getColumn(4).setPreferredWidth(150);
        jtSesiones.getColumnModel().getColumn(5).setPreferredWidth(100);
        jtSesiones.getColumnModel().getColumn(6).setPreferredWidth(200);
        jtSesiones.getColumnModel().getColumn(7).setPreferredWidth(80);

        jtSesiones.setShowGrid(true);
        jtSesiones.setGridColor(Color.LIGHT_GRAY);
    }
    
    private void cargarSesiones() {
        try {
            modelo.setRowCount(0);
            
            if (sesionData == null) {
                JOptionPane.showMessageDialog(this, "Error: No se pudo conectar con la base de datos.");
                return;
            }
            
            ArrayList<Sesion> sesiones = sesionData.listarTodasLasSesiones();
            
            for (Sesion sesion : sesiones) {
                String nombreCliente = "N/A";
                if (sesion.getDiaDeSpa() != null && sesion.getDiaDeSpa().getCliente() != null) {
                    nombreCliente = sesion.getDiaDeSpa().getCliente().getApellido() + ", " + 
                                    sesion.getDiaDeSpa().getCliente().getNombre();
                }
                
                String fecha = sesion.getFechaHoraInicio() != null ? 
                    sesion.getFechaHoraInicio().format(formatoFecha) : "N/A";
                
                String horario = sesion.getFechaHoraInicio() != null ? 
                    sesion.getFechaHoraInicio().format(formatoHora) + " - " + 
                    (sesion.getFechaHoraFinal() != null ? sesion.getFechaHoraFinal().format(formatoHora) : "N/A") : "N/A";
                
                String tratamiento = sesion.getTratamiento() != null ? sesion.getTratamiento().getNombre() : "N/A";
                
                String masajista = sesion.getMasajista() != null ? 
                    sesion.getMasajista().getNombre() + " " + sesion.getMasajista().getApellido() : "N/A";
                
                String consultorio = sesion.getConsultorio() != null ? 
                    "Consultorio " + sesion.getConsultorio().getNroConsultorio() : "N/A";
                
                String instalaciones = "N/A";
                if (sesion.getInsalaciones() != null && !sesion.getInsalaciones().isEmpty()) {
                    StringBuilder sb = new StringBuilder();
                    for (int i = 0; i < sesion.getInsalaciones().size(); i++) {
                        if (i > 0) sb.append(", ");
                        sb.append(sesion.getInsalaciones().get(i).getNombre());
                    }
                    instalaciones = sb.toString();
                }
                
                String estado = sesion.isEstado() ? "Realizada" : "Cancelada";
                
                modelo.addRow(new Object[]{
                    fecha,
                    horario,
                    nombreCliente,
                    tratamiento,
                    masajista,
                    consultorio,
                    instalaciones,
                    estado
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las sesiones: " + e.getMessage());
            e.printStackTrace();
        }
    }
}

