/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Persistencia.InstalacionData;
import Persistencia.miConexion;
import control.ControlInstalaciones;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * @author Grupo10
 *
 * Altamirano Karina Gianfranco Antonacci Matías Bequis Marcos Ezequiel Dave
 * Natalia
 */
public class vistaInstalaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaInstalaciones
     */
    private InstalacionData instalacionData;
    private miConexion connection = null;
    private ControlInstalaciones controlInstalacion;
    
    DefaultTableModel model = new DefaultTableModel();
    
    public vistaInstalaciones() {
        initComponents();
        try {
            connection = new miConexion("jdbc:mariadb://localhost:3306/gp10_entre_dedos", "root", "");
            instalacionData = new InstalacionData(connection);            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos. " + e.getMessage());
        }        
        if(instalacionData != null){
            controlInstalacion = new ControlInstalaciones(this, instalacionData);
        }
        configurarTabla();
        controlInstalacion.listarInstalaciones();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFiltros = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInstalaciones = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jrbActivo = new javax.swing.JRadioButton();
        jrbInactivo = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfBuscarInstalaciones = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfPrecio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDetalle = new javax.swing.JTextArea();
        jcbEstado = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jbLimpiarCasilleros = new javax.swing.JButton();
        jbModificarInstalacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtfUsos = new javax.swing.JTextField();
        jbCargarInstalacion = new javax.swing.JButton();

        setBackground(new java.awt.Color(155, 216, 185));
        setClosable(true);
        setTitle("Instalaciones");
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBackground(new java.awt.Color(155, 216, 185));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(155, 216, 185));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Instalaciones");

        jtInstalaciones.setBackground(new java.awt.Color(155, 216, 185));
        jtInstalaciones.setForeground(new java.awt.Color(0, 0, 0));
        jtInstalaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Detalle", "Usos", "Precio", "Estado"
            }
        ));
        jtInstalaciones.setGridColor(new java.awt.Color(155, 216, 185));
        jtInstalaciones.setSelectionBackground(new java.awt.Color(0, 51, 51));
        jtInstalaciones.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jtInstalaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtInstalacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtInstalaciones);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("(Selecionar una instalción para modficiar)");

        bgFiltros.add(jrbActivo);
        jrbActivo.setForeground(new java.awt.Color(0, 0, 0));
        jrbActivo.setText("Activo");
        jrbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbActivoActionPerformed(evt);
            }
        });

        bgFiltros.add(jrbInactivo);
        jrbInactivo.setForeground(new java.awt.Color(0, 0, 0));
        jrbInactivo.setText("Inactivo");
        jrbInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInactivoActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Filtros:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Buscar por Nombre:");

        jtfBuscarInstalaciones.setBackground(new java.awt.Color(202, 243, 222));
        jtfBuscarInstalaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarInstalacionesKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBuscarInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbActivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbInactivo)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jrbActivo)
                    .addComponent(jrbInactivo)
                    .addComponent(jtfBuscarInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(155, 216, 185));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificar Instalaciones");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Detalle:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio:");

        jtfNombre.setBackground(new java.awt.Color(202, 243, 222));

        jtfPrecio.setBackground(new java.awt.Color(202, 243, 222));

        jtaDetalle.setBackground(new java.awt.Color(202, 243, 222));
        jtaDetalle.setColumns(20);
        jtaDetalle.setRows(5);
        jScrollPane2.setViewportView(jtaDetalle);

        jcbEstado.setForeground(new java.awt.Color(0, 0, 0));
        jcbEstado.setText("Activo");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estado:");

        jbLimpiarCasilleros.setBackground(new java.awt.Color(155, 216, 185));
        jbLimpiarCasilleros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-limpieza.png"))); // NOI18N
        jbLimpiarCasilleros.setText("Limpiar casilleros");
        jbLimpiarCasilleros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarCasillerosActionPerformed(evt);
            }
        });

        jbModificarInstalacion.setBackground(new java.awt.Color(155, 216, 185));
        jbModificarInstalacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-editar-registro.png"))); // NOI18N
        jbModificarInstalacion.setText("Modificar Instalación");
        jbModificarInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarInstalacionActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Usos:");

        jtfUsos.setBackground(new java.awt.Color(202, 243, 222));

        jbCargarInstalacion.setBackground(new java.awt.Color(155, 216, 185));
        jbCargarInstalacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-nuevo-registro.png"))); // NOI18N
        jbCargarInstalacion.setText("Cargar Instalación");
        jbCargarInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarInstalacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbEstado)
                                    .addComponent(jtfUsos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jbModificarInstalacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbLimpiarCasilleros, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbCargarInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfUsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbEstado)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jbLimpiarCasilleros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCargarInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbModificarInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //--- Filtrar Instalaciones Activas ---
    private void jrbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbActivoActionPerformed
        controlInstalacion.listarInstalaciones();
    }//GEN-LAST:event_jrbActivoActionPerformed

    //--- Filtrar Instalaciones Inactivas ---
    private void jrbInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInactivoActionPerformed
        controlInstalacion.listarInstalaciones();
    }//GEN-LAST:event_jrbInactivoActionPerformed

    //--- Cargar a la base de datos una Instalacion ---
    private void jbCargarInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarInstalacionActionPerformed
        // TODO add your handling code here:
        controlInstalacion.cargarInstalaciones();
    }//GEN-LAST:event_jbCargarInstalacionActionPerformed

    //--- Botón de limpiar casilleros ---
    private void jbLimpiarCasillerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarCasillerosActionPerformed
        // TODO add your handling code here:
        controlInstalacion.limpiarCasilleros();
    }//GEN-LAST:event_jbLimpiarCasillerosActionPerformed

    //--- Seleccionar en la tabla una fila ---
    private void jtInstalacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtInstalacionesMouseClicked
        // TODO add your handling code here:
        controlInstalacion.seleccionarInstalacion();
    }//GEN-LAST:event_jtInstalacionesMouseClicked

    //--- Botón modificar instalacion ---
    private void jbModificarInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarInstalacionActionPerformed
        // TODO add your handling code here:
        controlInstalacion.modificarInstalaciones();
    }//GEN-LAST:event_jbModificarInstalacionActionPerformed

    //--- JTextFiel de Buscar Instalaciones al escribir ---
    private void jtfBuscarInstalacionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarInstalacionesKeyReleased
        // TODO add your handling code here:
        controlInstalacion.buscarInstalaciones();
    }//GEN-LAST:event_jtfBuscarInstalacionesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCargarInstalacion;
    private javax.swing.JButton jbLimpiarCasilleros;
    private javax.swing.JButton jbModificarInstalacion;
    private javax.swing.JCheckBox jcbEstado;
    private javax.swing.JRadioButton jrbActivo;
    private javax.swing.JRadioButton jrbInactivo;
    private javax.swing.JTable jtInstalaciones;
    private javax.swing.JTextArea jtaDetalle;
    private javax.swing.JTextField jtfBuscarInstalaciones;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfUsos;
    // End of variables declaration//GEN-END:variables

    //Metodos
     //--------- Configurar Tabla ---------
    public void configurarTabla(){
        
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Detalle");
        model.addColumn("Usos");
        model.addColumn("Precio");
        model.addColumn("Estado");
        
        jtInstalaciones.setModel(model);
    }
    
    //Getters y Setters
    public String getJtfNombre(){
        return jtfNombre.getText();
    }
    
    public void setJtfNombre(String setJtfNombre){
        this.jtfNombre.setText(setJtfNombre);
    }
    
    public String getJtaDetalle(){
        return jtaDetalle.getText();
    }
    
    public void setJtaDetalle(String setJtaDetalle){
        this.jtaDetalle.setText(setJtaDetalle);
    }
    
    public String getJtfPrecio(){
        return jtfPrecio.getText();
    }
    
    public void setJtfPrecio(String setJtfPrecio){
        this.jtfPrecio.setText(setJtfPrecio);
    }
    
    public String getJtfUsos(){
        return jtfUsos.getText();
    }
    
    public void setJtfUsos(String setJtfUsos){
        this.jtfUsos.setText(setJtfUsos);
    }
    
    public String getJtfBuscarInstalacion(){
        return jtfBuscarInstalaciones.getText();
    }
    
    public void setJtfBuscarInstalacion(String setJtfBuscarInstalacion){
        this.jtfBuscarInstalaciones.setText(setJtfBuscarInstalacion);
    }
    
    public boolean getJcbEstado(){
        if(jcbEstado.isSelected()){
            return true;
        }else{
            return false;
        }
    }
    
    public void setJtcbEstado(boolean setJtcbEstado){
        if(setJtcbEstado == true){
            this.jcbEstado.setSelected(true);
        }else{
            this.jcbEstado.setSelected(false);
        }
    }
    
    public boolean getJrbActivo(){
        if(jrbActivo.isSelected()){
            return true;
        }else{
            return false;
        }
    }
    
    public void setJrbActivo(boolean setJrbActivo){
        if(setJrbActivo == true){
            this.jrbActivo.setSelected(true);
        }else{
            this.jrbActivo.setSelected(false);
        }
    }
    
    public boolean getJrbInactivo(){
        if(jrbInactivo.isSelected()){
            return true;
        }else{
            return false;
        }
    }
    
    public void setJrbInactivo(boolean setJrbInactivo){
        if(setJrbInactivo == true){
            this.jrbInactivo.setSelected(true);
        }else{
            this.jrbInactivo.setSelected(false);
        }
    }

    // Método para resetear ambos radio buttons del filtro
    public void resetearFiltrosEstado(){
        bgFiltros.clearSelection();
    }
    
    public JTable getJtInstalaciones() {
        return jtInstalaciones;
    }

    public DefaultTableModel getModel() {
        return model;
    }

    public void setModel(DefaultTableModel model) {
        this.model = model;
    }
    
}
