/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Persistencia.*;
import control.ControlMasajista;
import control.ControlVistaEmpleados;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
  * @author Grupo10
 *
 * Altamirano Karina Gianfranco Antonacci Matías Bequis Marcos Ezequiel Dave
 * Natalia
 */
public class vistaEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaEmpleados
     */
    
    private final JDesktopPane Escritorio;
    private miConexion connection = null;
    private MasajistaData masajistaData = null;
    private VendedorData vendedorData = null;
    private ControlVistaEmpleados controlVistaEmpleados = null;

    public vistaEmpleados(JDesktopPane escritorio) {
        this.Escritorio = escritorio;
        initComponents();
        
        try {
            connection = new miConexion("jdbc:mariadb://localhost:3306/gp10_entre_dedos", "root", "");
            masajistaData = new MasajistaData(connection);
            vendedorData = new VendedorData(connection);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos. " + e.getMessage());
        }

        if (masajistaData != null && vendedorData != null) {
            this.controlVistaEmpleados = new ControlVistaEmpleados(this, masajistaData, vendedorData, Escritorio);
            controlVistaEmpleados.preCargarCbTipoDeEmpleado();
            controlVistaEmpleados.agregarListenerTipoEmpleado();
            controlVistaEmpleados.actualizarTabla();
        }
    }

    // Busca si ya existe un JInternalFrame en el JDesktopPane
    private JInternalFrame buscarFrame(Class<? extends JInternalFrame> clase) {
        for (JInternalFrame f : Escritorio.getAllFrames()) {
            if (clase.isInstance(f)) return f;
        }
        return null;
    }
    
    private void centrarFrame(JInternalFrame f) {
        int x = (Escritorio.getWidth() - f.getWidth()) / 2;
        int y = (Escritorio.getHeight() - f.getHeight()) / 2;
        f.setLocation(Math.max(x, 0), Math.max(y, 0));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbTipoDeEmpleado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmpleados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnModfActivoOInactivo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarMasajista = new javax.swing.JButton();
        btnRegistrarVendedor = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBusquedaPorDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBusquedaPorId = new javax.swing.JTextField();
        txtBusquedaPorMatricula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbEspecialidades = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnLimpiarCampos = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setTitle("Gestion de Empleados");
        setPreferredSize(new java.awt.Dimension(1112, 650));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(115, 179, 147));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 646));

        cbTipoDeEmpleado.setBackground(new java.awt.Color(155, 216, 185));
        cbTipoDeEmpleado.setForeground(new java.awt.Color(155, 216, 185));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tipo de empleado:");

        jtEmpleados.setBackground(new java.awt.Color(155, 216, 185));
        jtEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        jtEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtEmpleados.setGridColor(new java.awt.Color(155, 216, 185));
        jtEmpleados.setSelectionBackground(new java.awt.Color(0, 51, 51));
        jScrollPane1.setViewportView(jtEmpleados);

        jButton1.setBackground(new java.awt.Color(155, 216, 185));
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnModfActivoOInactivo.setBackground(new java.awt.Color(155, 216, 185));
        btnModfActivoOInactivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-activo-inactivo.png"))); // NOI18N
        btnModfActivoOInactivo.setText("Modif. Activo / Inactivo");
        btnModfActivoOInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModfActivoOInactivoActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(155, 216, 185));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-editar-registro.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("(Para modificar es necesario seleccionar una fila)");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnRegistrarMasajista.setBackground(new java.awt.Color(155, 216, 185));
        btnRegistrarMasajista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-registrar-empleado.png"))); // NOI18N
        btnRegistrarMasajista.setText("Registrar Masajista");
        btnRegistrarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMasajistaActionPerformed(evt);
            }
        });

        btnRegistrarVendedor.setBackground(new java.awt.Color(155, 216, 185));
        btnRegistrarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-registrar-empleado.png"))); // NOI18N
        btnRegistrarVendedor.setText("Registrar Vendedor");
        btnRegistrarVendedor.setMaximumSize(new java.awt.Dimension(156, 31));
        btnRegistrarVendedor.setMinimumSize(new java.awt.Dimension(156, 31));
        btnRegistrarVendedor.setPreferredSize(new java.awt.Dimension(156, 31));
        btnRegistrarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVendedorActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(155, 216, 185));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Busqueda por DNI:");

        txtBusquedaPorDni.setBackground(new java.awt.Color(155, 216, 185));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Busqueda por ID:");

        txtBusquedaPorId.setBackground(new java.awt.Color(155, 216, 185));

        txtBusquedaPorMatricula.setBackground(new java.awt.Color(155, 216, 185));
        txtBusquedaPorMatricula.setText("(Funcion solo para masajistas)");
        txtBusquedaPorMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaPorMatriculaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Busqueda por Matricula:");

        cbEspecialidades.setBackground(new java.awt.Color(155, 216, 185));
        cbEspecialidades.setForeground(new java.awt.Color(155, 216, 185));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Especialidad");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setText("(Funcion solo para masajistas)");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Para editar un empleado: haga doble clic en una celda, ingrese el nuevo valor y presione ‘Modificar’");

        btnLimpiarCampos.setBackground(new java.awt.Color(155, 216, 185));
        btnLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-limpieza.png"))); // NOI18N
        btnLimpiarCampos.setText("limpiar campos");
        btnLimpiarCampos.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(155, 216, 185));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-actualizar.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addComponent(cbEspecialidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTipoDeEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(487, 487, 487))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBusquedaPorDni, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtBusquedaPorId))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtBusquedaPorMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModificar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnModfActivoOInactivo))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegistrarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRegistrarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbTipoDeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBusquedaPorDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBusquedaPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusquedaPorMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnLimpiarCampos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModfActivoOInactivo)
                    .addComponent(btnModificar)
                    .addComponent(jButton1))
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModfActivoOInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModfActivoOInactivoActionPerformed
        // TODO add your handling code here:
        controlVistaEmpleados.cambiarEstadoSeleccionado();
    }//GEN-LAST:event_btnModfActivoOInactivoActionPerformed

    private void txtBusquedaPorMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaPorMatriculaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBusquedaPorMatriculaActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        // TODO add your handling code here:
        txtBusquedaPorDni.setText("");
        txtBusquedaPorId.setText("");
        txtBusquedaPorMatricula.setText("");
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnRegistrarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMasajistaActionPerformed
        // TODO add your handling code here:
        JInternalFrame abierto = buscarFrame(vistaCargarMasajista.class);
        if (abierto != null) {
            try { abierto.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
            abierto.toFront();
            centrarFrame(abierto);
            return;
        }

        vistaCargarMasajista frm = new vistaCargarMasajista();
        Escritorio.add(frm);
        frm.pack(); 
        centrarFrame(frm);
        frm.setVisible(true);
        try { 
            frm.setSelected(true); 
        } catch (java.beans.PropertyVetoException e) {}
        
    }//GEN-LAST:event_btnRegistrarMasajistaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegistrarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVendedorActionPerformed
        // TODO add your handling code here:
        JInternalFrame abierto = buscarFrame(vistaCargarVendedor.class);
        if (abierto != null) {
            try { abierto.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
            abierto.toFront();
            centrarFrame(abierto);
            return;
        }

        vistaCargarVendedor frm = new vistaCargarVendedor();
        Escritorio.add(frm);
        frm.pack(); 
        centrarFrame(frm);
        frm.setVisible(true);
        try { 
            frm.setSelected(true); 
        } catch (java.beans.PropertyVetoException e) {}
        
    }//GEN-LAST:event_btnRegistrarVendedorActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        controlVistaEmpleados.actualizarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        controlVistaEmpleados.modificarEmpleadoSeleccionado();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        controlVistaEmpleados.buscarEmpleado();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnModfActivoOInactivo;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrarMasajista;
    private javax.swing.JButton btnRegistrarVendedor;
    private javax.swing.JComboBox<String> cbEspecialidades;
    private javax.swing.JComboBox<String> cbTipoDeEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtEmpleados;
    private javax.swing.JTextField txtBusquedaPorDni;
    private javax.swing.JTextField txtBusquedaPorId;
    private javax.swing.JTextField txtBusquedaPorMatricula;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbEspecialidades() {
        return cbEspecialidades;
    }

    public void setCbEspecialidades(JComboBox<String> cbEspecialidades) {
        this.cbEspecialidades = cbEspecialidades;
    }

    public JComboBox<String> getCbTipoDeEmpleado() {
        return cbTipoDeEmpleado;
    }

    public void setCbTipoDeEmpleado(JComboBox<String> cbTipoDeEmpleado) {
        this.cbTipoDeEmpleado = cbTipoDeEmpleado;
    }

    public JTable getJtEmpleados() {
        return jtEmpleados;
    }

    public void setJtEmpleados(JTable jtEmpleados) {
        this.jtEmpleados = jtEmpleados;
    }

    public JTextField getTxtBusquedaPorDni() {
        return txtBusquedaPorDni;
    }

    public void setTxtBusquedaPorDni(JTextField txtBusquedaPorDni) {
        this.txtBusquedaPorDni = txtBusquedaPorDni;
    }

    public JTextField getTxtBusquedaPorId() {
        return txtBusquedaPorId;
    }

    public void setTxtBusquedaPorId(JTextField txtBusquedaPorId) {
        this.txtBusquedaPorId = txtBusquedaPorId;
    }

    public JTextField getTxtBusquedaPorMatricula() {
        return txtBusquedaPorMatricula;
    }

    public void setTxtBusquedaPorMatricula(JTextField txtBusquedaPorMatricula) {
        this.txtBusquedaPorMatricula = txtBusquedaPorMatricula;
    }
}
