/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.applet.AudioClip;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author matia
 */
public class vistaMenuSpa extends javax.swing.JFrame {

    /**
     * Creates new form vistaMenuSpa
     */
    public vistaMenuSpa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        musica();
        //estiloBoton();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new resources.img.ImagenFondo();
        jbPlay = new javax.swing.JButton();
        jbStop = new javax.swing.JButton();
        jpFondoMenu = new resources.img.ImagenMenu();
        jButton3 = new javax.swing.JButton();
        jbConsultorios = new javax.swing.JButton();
        jbCargarSesion = new javax.swing.JButton();
        jbCargarCliente1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbEmpleados = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmVerEmpleados = new javax.swing.JMenuItem();
        lmCargarMasajista = new javax.swing.JMenuItem();
        lmCargarVendedor = new javax.swing.JMenuItem();
        jmTratamientos = new javax.swing.JMenu();
        jmVerTratamientos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spa Grupo 10");

        Escritorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPlay.setBackground(new java.awt.Color(155, 216, 185));
        jbPlay.setForeground(new java.awt.Color(0, 0, 0));
        jbPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-play.png"))); // NOI18N
        jbPlay.setText("Play");
        jbPlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbPlay.setBorderPainted(false);
        jbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPlayMouseClicked(evt);
            }
        });

        jbStop.setBackground(new java.awt.Color(155, 216, 185));
        jbStop.setForeground(new java.awt.Color(0, 0, 0));
        jbStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icono-stop.png"))); // NOI18N
        jbStop.setText("Stop");
        jbStop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbStop.setBorderPainted(false);
        jbStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbStopMouseClicked(evt);
            }
        });

        jpFondoMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setBackground(new java.awt.Color(155, 216, 185));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Tienda");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setBorderPainted(false);

        jbConsultorios.setBackground(new java.awt.Color(155, 216, 185));
        jbConsultorios.setForeground(new java.awt.Color(0, 0, 0));
        jbConsultorios.setText("Consultorios");
        jbConsultorios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbConsultorios.setBorderPainted(false);

        jbCargarSesion.setBackground(new java.awt.Color(155, 216, 185));
        jbCargarSesion.setForeground(new java.awt.Color(0, 0, 0));
        jbCargarSesion.setText("Cargar Sesión");
        jbCargarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbCargarSesion.setBorderPainted(false);
        jbCargarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarSesionActionPerformed(evt);
            }
        });

        jbCargarCliente1.setBackground(new java.awt.Color(155, 216, 185));
        jbCargarCliente1.setForeground(new java.awt.Color(0, 0, 0));
        jbCargarCliente1.setText("Cliente");
        jbCargarCliente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbCargarCliente1.setBorderPainted(false);
        jbCargarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarCliente1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(155, 216, 185));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Reservas");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbEmpleados.setBackground(new java.awt.Color(155, 216, 185));
        jbEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        jbEmpleados.setText("Empleados");
        jbEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbEmpleados.setBorderPainted(false);
        jbEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondoMenuLayout = new javax.swing.GroupLayout(jpFondoMenu);
        jpFondoMenu.setLayout(jpFondoMenuLayout);
        jpFondoMenuLayout.setHorizontalGroup(
            jpFondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoMenuLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jpFondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbConsultorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCargarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCargarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jpFondoMenuLayout.setVerticalGroup(
            jpFondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoMenuLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jbCargarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCargarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Escritorio.setLayer(jbPlay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jbStop, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jpFondoMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFondoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 658, Short.MAX_VALUE)
                .addComponent(jbPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbStop, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addContainerGap(675, Short.MAX_VALUE)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbStop, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFondoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu2.setText("Empleados");

        jmVerEmpleados.setText("Ver Empleados");
        jmVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVerEmpleadosActionPerformed(evt);
            }
        });
        jMenu2.add(jmVerEmpleados);

        lmCargarMasajista.setText("Cargar Masajista");
        lmCargarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmCargarMasajistaActionPerformed(evt);
            }
        });
        jMenu2.add(lmCargarMasajista);

        lmCargarVendedor.setText("Cargar Vendedor");
        lmCargarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmCargarVendedorActionPerformed(evt);
            }
        });
        jMenu2.add(lmCargarVendedor);

        jMenuBar1.add(jMenu2);

        jmTratamientos.setText("Tratamientos");
        jmTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTratamientosActionPerformed(evt);
            }
        });

        jmVerTratamientos.setText("Ver Tratamientos");
        jmVerTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVerTratamientosActionPerformed(evt);
            }
        });
        jmTratamientos.add(jmVerTratamientos);

        jMenuBar1.add(jmTratamientos);

        jMenu3.setText("Busquedas");

        jMenuItem4.setText("Historial de Sesiones/Turnos");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Historial de Clientes");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Historial de Tratamientos");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Tienda");

        jMenuItem7.setText("Historial de Ventas");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Historial de Productos");
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbStopMouseClicked
        // TODO add your handling code here:
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/resources/sounds/wet_hands_c418.wav"));
        sound.stop();
    }//GEN-LAST:event_jbStopMouseClicked

    private void jbPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPlayMouseClicked
        musica();
    }//GEN-LAST:event_jbPlayMouseClicked

    private void jbCargarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarSesionActionPerformed
        vistaCargarSesion ventana = new vistaCargarSesion();
        Escritorio.add(ventana);
        // Centrar la ventana en el Escritorio
        int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);
        ventana.setVisible(true);
    }//GEN-LAST:event_jbCargarSesionActionPerformed

    private void jbCargarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarCliente1ActionPerformed
        vistaCargarCliente ventana = new vistaCargarCliente();
        Escritorio.add(ventana);
        // Centrar la ventana en el Escritorio
        int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);
        ventana.setVisible(true);
    }//GEN-LAST:event_jbCargarCliente1ActionPerformed

    private void jmTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTratamientosActionPerformed
        vistaTratamientos ventana = new vistaTratamientos();
        Escritorio.add(ventana);
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof vistaTratamientos) {
                frame.toFront();
                return;
            }
        }
    }//GEN-LAST:event_jmTratamientosActionPerformed

    private void jmVerTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVerTratamientosActionPerformed
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof vistaTratamientos) {
                frame.toFront();
                return;
            }
        }

        vistaTratamientos ventana = new vistaTratamientos();
        Escritorio.add(ventana);
        ventana.setSize(650, 500);
        int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);
        ventana.setVisible(true);
    }//GEN-LAST:event_jmVerTratamientosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        vistaReservas ventana = new vistaReservas();
        Escritorio.add(ventana);
        // Centrar la ventana en el Escritorio
        int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);
        ventana.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmpleadosActionPerformed
        // TODO add your handling code here:
        vistaEmpleados ventana = null;

        // Buscar si ya existe una instancia en el escritorio
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof vistaEmpleados) {
                ventana = (vistaEmpleados) frame;
                break;
            }
        }

        if (ventana == null) {
            // Crear nueva si no estaba abierta la ventana
            ventana = new vistaEmpleados(Escritorio);
            // Instanciarla
            Escritorio.add(ventana);

            // Centrar
            int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
            int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
            ventana.setLocation(x, y);

            ventana.setVisible(true);
        } else {
            // Si ya estaba, traerla al frente
            try {
                ventana.setIcon(false); // restaurar si estaba minimizada
                ventana.setSelected(true);
                ventana.toFront();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbEmpleadosActionPerformed

    private void jmVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVerEmpleadosActionPerformed
        // TODO add your handling code here:
        vistaEmpleados ventana = null;

        // Buscar si ya existe una instancia en el escritorio
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof vistaEmpleados) {
                ventana = (vistaEmpleados) frame;
                break;
            }
        }

        if (ventana == null) {
            // Crear nueva si no estaba abierta la ventana
            ventana = new vistaEmpleados(Escritorio);
            // Instanciarla
            Escritorio.add(ventana);

            // Centrar
            int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
            int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
            ventana.setLocation(x, y);

            ventana.setVisible(true);
        } else {
            // Si ya estaba, traerla al frente
            try {
                ventana.setIcon(false); // restaurar si estaba minimizada
                ventana.setSelected(true);
                ventana.toFront();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jmVerEmpleadosActionPerformed

    private void lmCargarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmCargarVendedorActionPerformed
        // TODO add your handling code here: 
        vistaCargarVendedor ventana = null;

        // Buscar si ya existe una instancia en el escritorio
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof vistaCargarVendedor) {
                ventana = (vistaCargarVendedor) frame;
                break;
            }
        }

        if (ventana == null) {
            // Crear nueva si no estaba abierta la ventana
            ventana = new vistaCargarVendedor();
            // Instanciarla
            Escritorio.add(ventana);

            // Centrar
            int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
            int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
            ventana.setLocation(x, y);

            ventana.setVisible(true);
        } else {
            // Si ya estaba, traerla al frente
            try {
                ventana.setIcon(false); // restaurar si estaba minimizada
                ventana.setSelected(true);
                ventana.toFront();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_lmCargarVendedorActionPerformed

    private void lmCargarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmCargarMasajistaActionPerformed
        // TODO add your handling code here:
        vistaCargarMasajista ventana = null;

        // Buscar si ya existe una instancia en el escritorio
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof vistaCargarMasajista) {
                ventana = (vistaCargarMasajista) frame;
                break;
            }
        }

        if (ventana == null) {
            // Crear nueva si no estaba abierta la ventana
            ventana = new vistaCargarMasajista();
            // Instanciarla
            Escritorio.add(ventana);

            // Centrar
            int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
            int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
            ventana.setLocation(x, y);

            ventana.setVisible(true);
        } else {
            // Si ya estaba, traerla al frente
            try {
                ventana.setIcon(false); // restaurar si estaba minimizada
                ventana.setSelected(true);
                ventana.toFront();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_lmCargarMasajistaActionPerformed

    public void musica() {
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/resources/sounds/wet_hands_c418.wav"));
        sound.loop();
        sound.play();
    }

    public void estiloBoton() {
        jbConsultorios.setBorder(
                BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(0, 128, 0), 2), // borde exterior
                        BorderFactory.createEmptyBorder(5, 10, 5, 10) // margen interno
                )
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaMenuSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaMenuSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaMenuSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaMenuSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaMenuSpa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JButton jbCargarCliente1;
    private javax.swing.JButton jbCargarSesion;
    private javax.swing.JButton jbConsultorios;
    private javax.swing.JButton jbEmpleados;
    private javax.swing.JButton jbPlay;
    private javax.swing.JButton jbStop;
    private javax.swing.JMenu jmTratamientos;
    private javax.swing.JMenuItem jmVerEmpleados;
    private javax.swing.JMenuItem jmVerTratamientos;
    private javax.swing.JPanel jpFondoMenu;
    private javax.swing.JMenuItem lmCargarMasajista;
    private javax.swing.JMenuItem lmCargarVendedor;
    // End of variables declaration//GEN-END:variables


    // Busca si ya está abierto un frame de ese tipo
    private JInternalFrame buscarFrame(Class<? extends JInternalFrame> clase) {
        for (JInternalFrame f : Escritorio.getAllFrames()) {
            if (clase.isInstance(f)) {
                return f;
            }
        }
        return null;
    }
}
