/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Persistencia.ClienteData;
import Persistencia.DiaDeSpaData;
import Persistencia.SesionData;
import Persistencia.miConexion;
import entidades.Cliente;
import entidades.DiaDeSpa;
import entidades.Sesion;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 * @author Grupo10
 *
 * Altamirano Karina Gianfranco Antonacci Matías Bequis Marcos Ezequiel Dave
 * Natalia
 */
public class vistaHistorialClientes extends javax.swing.JInternalFrame {

    private miConexion connection;
    private ClienteData clienteData;
    private DiaDeSpaData diaDeSpaData;
    private SesionData sesionData;
    private DateTimeFormatter formatoFecha;
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    /**
     * Creates new form vistaHistorialClientes
     */
    public vistaHistorialClientes() {
        initComponents();
        this.getContentPane().setBackground(new Color(155, 216, 185));
        try {
            connection = new miConexion("jdbc:mariadb://localhost:3306/gp10_entre_dedos", "root", "");
            clienteData = new ClienteData(connection);
            diaDeSpaData = new DiaDeSpaData(connection);
            sesionData = new SesionData(connection);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage());
        }
        
        formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        armarCabecera();
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        jbActualizar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Historial de Clientes");

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jtClientes);

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbActualizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        cargarClientes();
    }//GEN-LAST:event_jbActualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JTable jtClientes;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.setRowCount(0);
        modelo.setColumnCount(0);
        
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Fecha Ingreso");
        modelo.addColumn("Tratamiento");
        modelo.addColumn("Fecha de Tratamiento");
        modelo.addColumn("Estado");
        
        jtClientes.setModel(modelo);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        jtClientes.getTableHeader().setDefaultRenderer(centerRenderer);

        DefaultTableCellRenderer centrarCeldas = new DefaultTableCellRenderer();
        centrarCeldas.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < jtClientes.getColumnCount(); i++) {
            jtClientes.getColumnModel().getColumn(i).setCellRenderer(centrarCeldas);
        }
        
        jtClientes.getColumnModel().getColumn(0).setPreferredWidth(100);
        jtClientes.getColumnModel().getColumn(1).setPreferredWidth(150);
        jtClientes.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtClientes.getColumnModel().getColumn(3).setPreferredWidth(120);
        jtClientes.getColumnModel().getColumn(4).setPreferredWidth(120);
        jtClientes.getColumnModel().getColumn(5).setPreferredWidth(200);
        jtClientes.getColumnModel().getColumn(6).setPreferredWidth(150);
        jtClientes.getColumnModel().getColumn(7).setPreferredWidth(100);

        jtClientes.setShowGrid(true);
        jtClientes.setGridColor(Color.LIGHT_GRAY);
    }
    
    private void cargarClientes() {
        try {
            modelo.setRowCount(0);
            
            if (clienteData == null || diaDeSpaData == null || sesionData == null) {
                JOptionPane.showMessageDialog(this, "Error: No se pudo conectar con la base de datos.");
                return;
            }
            
            ArrayList<Cliente> clientes = clienteData.listarClientes();
            
            for (Cliente cliente : clientes) {
                // Obtener todos los días de spa del cliente
                ArrayList<DiaDeSpa> diasDeSpa = diaDeSpaData.listarDiaDeSpas();
                ArrayList<DiaDeSpa> diasDelCliente = new ArrayList<>();
                
                for (DiaDeSpa dia : diasDeSpa) {
                    if (dia.getCliente() != null && dia.getCliente().getCodCli() == cliente.getCodCli()) {
                        diasDelCliente.add(dia);
                    }
                }
                
                // Obtener la fecha de ingreso (fecha del primer día de spa)
                String fechaIngreso = "N/A";
                if (!diasDelCliente.isEmpty()) {
                    DiaDeSpa primerDia = diasDelCliente.get(0);
                    for (DiaDeSpa dia : diasDelCliente) {
                        if (dia.getFechayhora().isBefore(primerDia.getFechayhora())) {
                            primerDia = dia;
                        }
                    }
                    fechaIngreso = primerDia.getFechayhora().format(formatoFecha);
                }
                
                String estado = cliente.isEstado() ? "Activo" : "Inactivo";
                
                // Obtener todas las sesiones del cliente y crear una fila por cada una
                ArrayList<Sesion> todasLasSesiones = new ArrayList<>();
                for (DiaDeSpa dia : diasDelCliente) {
                    ArrayList<Sesion> sesiones = sesionData.listarSesionesPorPack(dia.getCodPack());
                    for (Sesion sesion : sesiones) {
                        if (sesion.getTratamiento() != null && sesion.isEstado()) {
                            todasLasSesiones.add(sesion);
                        }
                    }
                }
                
                // Si el cliente no tiene sesiones, agregar una fila indicando que no tiene tratamientos
                if (todasLasSesiones.isEmpty()) {
                    modelo.addRow(new Object[]{
                        cliente.getDni(),
                        cliente.getNombre(),
                        cliente.getApellido(),
                        cliente.getTelefono(),
                        fechaIngreso,
                        "Sin tratamientos",
                        "N/A",
                        estado
                    });
                } else {
                    // Crear una fila por cada sesión/tratamiento
                    for (Sesion sesion : todasLasSesiones) {
                        String nombreTratamiento = sesion.getTratamiento() != null ? 
                            sesion.getTratamiento().getNombre() : "N/A";
                        String fechaTratamiento = sesion.getFechaHoraInicio() != null ? 
                            sesion.getFechaHoraInicio().format(formatoFecha) : "N/A";
                        
                        modelo.addRow(new Object[]{
                            cliente.getDni(),
                            cliente.getNombre(),
                            cliente.getApellido(),
                            cliente.getTelefono(),
                            fechaIngreso,
                            nombreTratamiento,
                            fechaTratamiento,
                            estado
                        });
                    }
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los clientes: " + e.getMessage());
            e.printStackTrace();
        }
    }
}

