/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Persistencia.ProductoData;
import Persistencia.miConexion;
import control.ControlTienda;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class vistaTienda extends javax.swing.JInternalFrame {

    private miConexion connection;
    private ProductoData productoData;
    private ControlTienda controlTienda;
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    
    private DefaultTableModel modeloVentas = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    /**
     * Creates new form vistaTienda
     */
    public vistaTienda() {
        initComponents();
        this.getContentPane().setBackground(new Color(155, 216, 185));
        armarCabecera();
        armarCabeceraVentas();

        try {
            connection = new miConexion("jdbc:mariadb://localhost:3306/gp10_entre_dedos", "root", "");

            productoData = new ProductoData(connection);

            if (productoData != null) {
                this.controlTienda = new ControlTienda(this, productoData);
                configurarListeners();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos (vistaTienda): " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*@SuppressWarnings("unchecked")*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcbVegano1 = new javax.swing.JCheckBox();
        jcbSinT1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTienda = new javax.swing.JTable();
        jbAgregarAVentas = new javax.swing.JButton();
        jbLimpiarTabladeVentas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVentas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jbEliminarArticuloDeVentas = new javax.swing.JButton();
        jbConfirmarVenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtFabricante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtDetalle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Stock = new javax.swing.JTextField();
        jcbProdVegano = new javax.swing.JCheckBox();
        jcbProdSinTacc = new javax.swing.JCheckBox();
        jbGuardarP = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(155, 216, 185));
        setClosable(true);
        setResizable(true);
        setTitle("Tienda");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Buscar Producto: ");

        jLabel7.setText("ID Producto:");

        jbBuscar.setText("Buscar");

        jLabel8.setText("Filtros:");

        jcbVegano1.setText("Producto Vegano");

        jcbSinT1.setText("Sin TACC");

        jtTienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre", "Fabricante", "Detalle", "Precio", "Stock", "Vegano", "Sin Tacc"
            }
        ));
        jScrollPane1.setViewportView(jtTienda);

        jbAgregarAVentas.setText("Agregar a Ventas");
        jbAgregarAVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarAVentasActionPerformed(evt);
            }
        });

        jbLimpiarTabladeVentas.setText("Limpiar Tabla de Ventas");
        jbLimpiarTabladeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarTabladeVentasActionPerformed(evt);
            }
        });

        jtVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre", "Fabricante", "Detalle", "Precio", "Stock", "Vegano", "SIn Tacc"
            }
        ));
        jScrollPane2.setViewportView(jtVentas);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Lista de Ventas");

        jbEliminarArticuloDeVentas.setText("Eliminar Artículo de Ventas");
        jbEliminarArticuloDeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarArticuloDeVentasActionPerformed(evt);
            }
        });

        jbConfirmarVenta.setText("Confirmar Venta");
        jbConfirmarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConfirmarVenta)
                .addGap(46, 46, 46)
                .addComponent(jbEliminarArticuloDeVentas)
                .addGap(43, 43, 43)
                .addComponent(jbLimpiarTabladeVentas)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jbBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jcbVegano1)
                                .addGap(18, 18, 18)
                                .addComponent(jcbSinT1)
                                .addGap(18, 18, 18)
                                .addComponent(jbAgregarAVentas))
                            .addComponent(jLabel6))))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(jLabel8)
                    .addComponent(jcbVegano1)
                    .addComponent(jcbSinT1)
                    .addComponent(jbAgregarAVentas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirmarVenta)
                    .addComponent(jbEliminarArticuloDeVentas)
                    .addComponent(jbLimpiarTabladeVentas))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre:");

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Fabricante:");

        jLabel3.setText("Detalle:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Stock:");

        jcbProdVegano.setText("Producto Vegano");

        jcbProdSinTacc.setText("Sin TACC");

        jbGuardarP.setText("Guardar Producto");

        jButton2.setText("Limpiar Campos");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Datos del Producto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtNombre)
                    .addComponent(jtPrecio)
                    .addComponent(jtDetalle)
                    .addComponent(jtFabricante)
                    .addComponent(Stock)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jButton2)
                            .addComponent(jbGuardarP)
                            .addComponent(jcbProdSinTacc)
                            .addComponent(jcbProdVegano))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jcbProdVegano)
                .addGap(18, 18, 18)
                .addComponent(jcbProdSinTacc)
                .addGap(18, 18, 18)
                .addComponent(jbGuardarP)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
        // Al presionar Enter en el campo nombre, pasa al siguiente campo
        jtFabricante.requestFocus();
    }                                        

    // Configura todos los listeners de los componentes
    
    private void configurarListeners() {
        if (controlTienda == null) {
            return;
        }

        // Listener para botón Guardar Producto
        jbGuardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarPActionPerformed(evt);
            }
        });

        // Listener para botón Buscar
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        // Listener para botón Limpiar Campos
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        // Listener para checkbox de filtro Vegano
        jcbVegano1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVegano1ActionPerformed(evt);
            }
        });

        // Listener para checkbox de filtro Sin TACC
        jcbSinT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSinT1ActionPerformed(evt);
            }
        });

        // NOTA: El listener para la tabla está configurado en ControlTienda
        // para evitar conflictos con la variable cargandoDesdeTabla
        // Listener para Enter en campo de búsqueda por ID
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        // Listeners para Enter en campos de texto del formulario
        jtFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDetalle.requestFocus();
            }
        });

        jtDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPrecio.requestFocus();
            }
        });

        jtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stock.requestFocus();
            }
        });

        Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarP.requestFocus();
            }
        });
    }

    /**
     * Acción del botón Guardar Producto
     */
    private void jbGuardarPActionPerformed(java.awt.event.ActionEvent evt) {
        if (controlTienda != null) {
            controlTienda.guardarOActualizarProducto();
        }
    }

    /**
     * Acción del botón Buscar
     */
    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {
        if (controlTienda != null) {
            controlTienda.buscarProductoPorId();
        }
    }

    /**
     * Acción del botón Limpiar Campos
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (controlTienda != null) {
            controlTienda.limpiarCampos();
        }
    }

    /**
     * Acción del checkbox de filtro Vegano
     */
    private void jcbVegano1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (controlTienda != null) {
            controlTienda.aplicarFiltros();
        }
    }

    /**
     * Acción del checkbox de filtro Sin TACC
     */
    private void jcbSinT1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (controlTienda != null) {
            controlTienda.aplicarFiltros();
        }
    }

    /**
     * Acción cuando se presiona Enter en el campo de búsqueda por ID
     */
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (controlTienda != null) {
            controlTienda.buscarProductoPorId();
        }

    }//GEN-LAST:event_jtNombreActionPerformed

    private void jbAgregarAVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarAVentasActionPerformed
        // TODO add your handling code here:
        if (controlTienda != null) {
            controlTienda.agregarProductoAVentas();
        }
  
    }//GEN-LAST:event_jbAgregarAVentasActionPerformed

    private void jbLimpiarTabladeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarTabladeVentasActionPerformed
        // TODO add your handling code here:
        if (controlTienda != null) {
            controlTienda.limpiarTablaVentas();
        }
    }//GEN-LAST:event_jbLimpiarTabladeVentasActionPerformed

    private void jbEliminarArticuloDeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarArticuloDeVentasActionPerformed
        // TODO add your handling code here:
        if (controlTienda != null) {
            controlTienda.eliminarArticuloDeVentas();
        }
    }//GEN-LAST:event_jbEliminarArticuloDeVentasActionPerformed

    private void jbConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarVentaActionPerformed
        // TODO add your handling code here:
        if (controlTienda != null) {
            controlTienda.confirmarVenta();
        }
    }//GEN-LAST:event_jbConfirmarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Stock;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbAgregarAVentas;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbConfirmarVenta;
    private javax.swing.JButton jbEliminarArticuloDeVentas;
    private javax.swing.JButton jbGuardarP;
    private javax.swing.JButton jbLimpiarTabladeVentas;
    private javax.swing.JCheckBox jcbProdSinTacc;
    private javax.swing.JCheckBox jcbProdVegano;
    private javax.swing.JCheckBox jcbSinT1;
    private javax.swing.JCheckBox jcbVegano1;
    private javax.swing.JTextField jtDetalle;
    private javax.swing.JTextField jtFabricante;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTable jtTienda;
    private javax.swing.JTable jtVentas;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {

        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fabricante");
        modelo.addColumn("Detalle");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        modelo.addColumn("Vegano");
        modelo.addColumn("Sin TACC");
        jtTienda.setModel(modelo);

    }
    
    private void armarCabeceraVentas() {
        modeloVentas.addColumn("ID");
        modeloVentas.addColumn("Nombre");
        modeloVentas.addColumn("Fabricante");
        modeloVentas.addColumn("Detalle");
        modeloVentas.addColumn("Precio");
        modeloVentas.addColumn("Cantidad");
        modeloVentas.addColumn("Vegano");
        modeloVentas.addColumn("Sin TACC");
        jtVentas.setModel(modeloVentas);
    }
    // Getters para acceso desde ControlTienda

    public javax.swing.JTextField getJtNombre() {
        return jtNombre;
    }

    public javax.swing.JTextField getJtFabricante() {
        return jtFabricante;
    }

    public javax.swing.JTextField getJtDetalle() {
        return jtDetalle;
    }

    public javax.swing.JTextField getJtPrecio() {
        return jtPrecio;
    }

    public javax.swing.JTextField getStock() {
        return Stock;
    }

    public javax.swing.JCheckBox getJcbProdVegano() {
        return jcbProdVegano;
    }

    public javax.swing.JCheckBox getJcbProdSinTacc() {
        return jcbProdSinTacc;
    }

    public javax.swing.JTextField getJTextField1() {
        return jTextField1;
    }

    public javax.swing.JButton getJbBuscar() {
        return jbBuscar;
    }

    public javax.swing.JButton getJbGuardarP() {
        return jbGuardarP;
    }

    public javax.swing.JButton getJButton2() {
        return jButton2;
    }

    public javax.swing.JTable getJtTienda() {
        return jtTienda;
    }

    public javax.swing.JCheckBox getJcbVegano1() {
        return jcbVegano1;
    }

    public javax.swing.JCheckBox getJcbSinT1() {
        return jcbSinT1;
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }
    
    public DefaultTableModel getModeloVentas() {
        return modeloVentas;
    }
    
    public javax.swing.JTable getJtVentas() {
        return jtVentas;
    }
    
    public javax.swing.JButton getJbConfirmarVenta() {
        return jbConfirmarVenta;
    }
    
    public javax.swing.JButton getJbEliminarArticuloDeVentas() {
        return jbEliminarArticuloDeVentas;
    }

}
