/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;


/**
 *
 * @author matia
 */
public class vistaCargarSesion extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaCargarSesion
     */
    public vistaCargarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfClienteSesion = new javax.swing.JTextField();
        jcbConsultorios = new javax.swing.JComboBox<>();
        jcbInstalaciones = new javax.swing.JComboBox<>();
        jcbMasajistas = new javax.swing.JComboBox<>();
        jbBuscarClienteSesion = new javax.swing.JButton();
        jbCargarClienteSesion = new javax.swing.JButton();
        jdcFechaInicial = new com.toedter.calendar.JDateChooser();
        jdcFechaFinal = new com.toedter.calendar.JDateChooser();
        jcbTratamientos = new javax.swing.JComboBox<>();
        jcbTiposTratamientos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jpDetalleSesion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jbCargarSesion = new javax.swing.JButton();
        jbLimpiarSesion = new javax.swing.JButton();
        jlToolTipTipoTratamiento = new javax.swing.JLabel();

        setBackground(new java.awt.Color(115, 179, 147));
        setClosable(true);
        setTitle("Cargar Sesion");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jpFondo.setBackground(new java.awt.Color(115, 179, 147));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cliente:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tratamiento:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Consultorio:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Instalaciones:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Masajistas:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha Inicial:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha Final:");

        jcbConsultorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 1: Masaje Corporal" }));

        jcbInstalaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zona 1: Café" }));

        jcbMasajistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juan Perez" }));

        jbBuscarClienteSesion.setText("Buscar");

        jbCargarClienteSesion.setText("Cargar");

        jdcFechaInicial.setDateFormatString("dd/MM/yyyy HH:mm");

        jdcFechaFinal.setDateFormatString("dd/MM/yyyy HH:mm");

        jcbTratamientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masaje Corporal" }));

        jcbTiposTratamientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exfoliación Corporal" }));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tipo de Tratamiento:");

        jpDetalleSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpDetalleSesionLayout = new javax.swing.GroupLayout(jpDetalleSesion);
        jpDetalleSesion.setLayout(jpDetalleSesionLayout);
        jpDetalleSesionLayout.setHorizontalGroup(
            jpDetalleSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jpDetalleSesionLayout.setVerticalGroup(
            jpDetalleSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("(Buscar por DNI)");

        jbCargarSesion.setText("Cargar Sesión");
        jbCargarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarSesionActionPerformed(evt);
            }
        });

        jbLimpiarSesion.setText("Limpiar");

        jlToolTipTipoTratamiento.setForeground(new java.awt.Color(0, 0, 0));
        jlToolTipTipoTratamiento.setText("O");
        jlToolTipTipoTratamiento.setToolTipText("[Descripción del tratamiento]");

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addContainerGap(56, Short.MAX_VALUE)
                        .addComponent(jpDetalleSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jdcFechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jcbTiposTratamientos, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfClienteSesion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcbTratamientos, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdcFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                                                .addGap(137, 137, 137)
                                                .addComponent(jLabel5))
                                            .addGroup(jpFondoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                                        .addComponent(jlToolTipTipoTratamiento)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4))
                                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                                        .addComponent(jbBuscarClienteSesion)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jbCargarClienteSesion)
                                                        .addGap(0, 40, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jLabel3)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbConsultorios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbInstalaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbMasajistas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbLimpiarSesion))))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCargarSesion)))
                .addGap(51, 51, 51))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfClienteSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarClienteSesion)
                    .addComponent(jbCargarClienteSesion))
                .addGap(33, 33, 33)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jcbTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jcbTiposTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jcbInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlToolTipTipoTratamiento))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdcFechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jcbMasajistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdcFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbLimpiarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jcbConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpDetalleSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCargarSesion)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCargarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarSesionActionPerformed
        // TODO add your handling code here:
        getJdcFechaInicial();
    }//GEN-LAST:event_jbCargarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbBuscarClienteSesion;
    private javax.swing.JButton jbCargarClienteSesion;
    private javax.swing.JButton jbCargarSesion;
    private javax.swing.JButton jbLimpiarSesion;
    private javax.swing.JComboBox<String> jcbConsultorios;
    private javax.swing.JComboBox<String> jcbInstalaciones;
    private javax.swing.JComboBox<String> jcbMasajistas;
    private javax.swing.JComboBox<String> jcbTiposTratamientos;
    private javax.swing.JComboBox<String> jcbTratamientos;
    private com.toedter.calendar.JDateChooser jdcFechaFinal;
    private com.toedter.calendar.JDateChooser jdcFechaInicial;
    private javax.swing.JLabel jlToolTipTipoTratamiento;
    private javax.swing.JPanel jpDetalleSesion;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JTextField jtfClienteSesion;
    // End of variables declaration//GEN-END:variables

    //-------- Getter y Setters de los atributos de la vista --------
    
    //Get del JTextField Cliente Sesión
    public int getJtClienteSesion(){
        return Integer.parseInt(jtfClienteSesion.getText());
    }
    
    public String getJcbTratamientos(){
        return (String)jcbTratamientos.getSelectedItem();
    }
    
    public String getJcbTiposTratamientos(){
        return (String)jcbTiposTratamientos.getSelectedItem();
    }
    
    public String getJcbConsultorios(){
        return (String)jcbConsultorios.getSelectedItem();
    }
    
    public String getJcbInstalaciones(){
        return (String)jcbInstalaciones.getSelectedItem();
    }
    
    public String getJcbMasajista(){
        return (String)jcbMasajistas.getSelectedItem();
    }
    
    public String getJdcFechaInicial(){
        Date sFechaInicial = jdcFechaInicial.getDate();
        LocalDateTime fechaInicial = sFechaInicial.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();        
        String formateada = fechaInicial.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
        
        return formateada;
    }
}
